[package]
name = "xdg-desktop-portal"
version = "0.1.0"
edition = "2024"
authors = ["dlzht"]

[dependencies]
serde = "1.0"
serde_repr = "0.1"
enumflags2 = "0.7"
zvariant = { version = "5.4", features = ["enumflags2"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }

[dev-dependencies]
tokio = { version = "1" , features = [ "full" ] }
